project:
  type: website
  output-dir: docs
  preview:
      port: 4001

website:
  title: "Straightbourne.github.io"
  site-url: https://Straightbourne.github.io
  search: false
  favicon: favicon.ico
  page-footer: 
    left: 
      - text: Copyright &copy; Nick Hood
  navbar:
    right:
      - icon: github
        href: https://github.com/Straightbourne
      - icon: instagram
        href: https://www.instagram.com/Straightbourne/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: 
      text: |
        <!-- Privacy-friendly analytics by Plausible -->
        <script async src="https://stats.sptr.net/js/pa-Ysqpinv0Bh8jFdBY-o2OF.js"></script>
        <script>
          window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
          plausible.init()
        </script>
